server:
  port: 8085

spring:
  application:
    # 应用名称
    name: @artifactId@
  profiles:
    # 环境配置
    active: @active@
  cloud:
    nacos:
      discovery:
        # 解决获取IP为内网，一般微服务采用内网安全性、可用性高
        # ip: 127.0.0.1
        # 服务注册地址
        server-addr: ${NACOS_HOST:twelvet-nacos}:${NACOS_PORT:8848}
        namespace: @nacos.namespace@
      config:
        # 配置中心地址
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        # 配置文件格式
        file-extension: yml
        # 命名空间
        namespace: @nacos.namespace@
        # 配置组
        group: DEFAULT_GROUP
        # 共享配置
        # shared-configs:
          # - data-id: twelvet-app-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
          # - data-id: twelvet-mail-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  config:
    import:
      - nacos:twelvet-app-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - nacos:twelvet-mail-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

    stream:
      rocketmq:
        binder:
          # 多个用;隔开
          name-server: twelvet-rocketmq:9876
          # Access Key ，可阅读 https://github.com/apache/rocketmq/blob/master/docs/cn/acl/user_guide.md 文档
          access-key:
          # Secret Key
          secret-key:
          # 是否开启消息轨迹功能。默认为 true 开启。可阅读 https://github.com/apache/rocketmq/blob/master/docs/cn/msg_trace/user_guide.md 文档
          enable-msg-trace: true
          # 自定义消息轨迹的 Topic 。默认为 RMQ_SYS_TRACE_TOPIC 。
          customized-trace-topic: RMQ_SYS_TRACE_TOPIC
      # 注册函数式Bean
      function:
        # 多个;分割
        definition: loginLog;operationLog
      bindings:
        # <functionName> + -in- + <index> 注意编写格式  生产者
        loginLog-out-0:
          # topic
          destination: twelvet-log-login
          # 分组
          group: system
          # json类型
          contentType: application/json
        # 消费者
        loginLog-in-0:
          # topic
          destination: twelvet-log-login
          # 文本类型
          content-type: text/plain
          # 分组
          group: system