version: '3'
services:
  twelvet-nacos:
    container_name: twelvet-nacos
    image: nacos/nacos-server:2.0.3
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    restart: always
    privileged: true
    build:
      context: ./nacos
    depends_on:
      - twelvet-mysql
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai

  twelvet-mysql:
    container_name: twelvet-mysql
    image: mysql:8.0
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
        'mysqld',
        '--innodb-buffer-pool-size=80M',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+8:00',
        '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_DATABASE: 'twelvet'
      MYSQL_ROOT_PASSWORD: 123456

  twelvet-redis:
    container_name: twelvet-redis
    image: redis
    privileged: true
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/twelvet/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/twelvet/redis/redis.conf

  twelvet-nginx:
    container_name: twelvet-nginx
    image: nginx
    environment:
      - TZ=Asia/Shanghai
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/home/twelvet/twelvet-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - twelvet-gateway
    links:
      - twelvet-gateway

  twelvet-gateway:
    container_name: twelvet-gateway
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    build:
      context: ./twelvet/gateway
      dockerfile: dockerfile

  twelvet-auth:
    container_name: twelvet-auth
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    build:
      context: ./twelvet/auth
      dockerfile: dockerfile
    depends_on:
      - twelvet-redis
      - twelvet-mysql
    links:
      - twelvet-redis
      - twelvet-mysql

  twelvet-server-system:
    container_name: twelvet-system
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    build:
      context: ./twelvet/server/system
      dockerfile: dockerfile
    depends_on:
      - twelvet-redis
      - twelvet-mysql
    links:
      - twelvet-redis
      - twelvet-mysql

  twelvet-server-es:
    container_name: twelvet-es
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    build:
      context: ./twelvet/server/es
      dockerfile: dockerfile

  twelvet-server-netty:
    container_name: twelvet-netty
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    build:
      context: ./twelvet/server/netty
      dockerfile: dockerfile

  twelvet-server-mq:
    container_name: twelvet-mq
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    build:
      context: ./twelvet/server/mq
      dockerfile: dockerfile

  twelvet-server-job:
    container_name: twelvet-job
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    build:
      context: ./twelvet/server/job
      dockerfile: dockerfile
    depends_on:
      - twelvet-mysql
    links:
      - twelvet-mysql

  twelvet-server-dfs:
    container_name: twelvet-dfs
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    build:
      context: ./twelvet/server/dfs
      dockerfile: dockerfile
    depends_on:
      - twelvet-mysql
    links:
      - twelvet-mysql

  twelvet-visual-monitor:
    container_name: twelvet-monitor
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    build:
      context: ./twelvet/visual/monitor
      dockerfile: dockerfile
