version: '3'
services:
  nacos:
    image: nacos/nacos-server:latest
    ports:
      - "8848:8848"
    restart: always
    privileged: true
    network_mode: twelvet-network
    volumes:
      - /data/docker/nacos/conf:/home/nacos/conf
      - /data/docker/nacos/data:/home/nacos/data
      - /data/docker/nacos/logs:/home/nacos/logs
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
  twelvet-gateway:
    image: docker.io/java:8
    restart: always
    container_name: twelvet-gateway
    privileged: true
    network_mode: twelvet-network
    # 可以接受外部输入
    tty: true
    ports:
      - 88:88
    volumes:
      - /data/docker/twelvet/logs/twelvet-gateway:/logs
      - /data/docker/twelvet/twelvet-gateway:/app
    entrypoint: 'java -DNACOS_HOST=${NACOS_HOST} -DNACOS_PORT=${NACOS_PORT} -Djava.security.egd=file:/dev/.urandom -jar -Xms128m -Xmx256m /app/twelvet-gateway.jar'
    environment:
      - JAVA_OPTS=-Xmx256M
      - TZ=Asia/Shanghai

  twelvet-auth:
    image: docker.io/java:8
    restart: always
    container_name: twelvet-auth
    privileged: true
    network_mode: twelvet-network
    # 可以接受外部输入
    tty: true
    volumes:
      - /data/docker/twelvet/logs/twelvet-auth:/logs
      - /data/docker/twelvet/twelvet-auth:/app
    entrypoint: 'java -DNACOS_HOST=${NACOS_HOST} -DNACOS_PORT=${NACOS_PORT} -Djava.security.egd=file:/dev/.urandom -jar -Xms128m -Xmx256m /app/twelvet-auth.jar'
    environment:
      - JAVA_OPTS=-Xmx256M
      - TZ=Asia/Shanghai

  twelvet-server-system:
    image: docker.io/java:8
    restart: always
    container_name: twelvet-system
    privileged: true
    network_mode: twelvet-network
    # 可以接受外部输入
    tty: true
    volumes:
      - /data/docker/twelvet/logs/twelvet-server-system:/logs
      - /data/docker/twelvet/twelvet-server-system:/app
    entrypoint: 'java -DNACOS_HOST=${NACOS_HOST} -DNACOS_PORT=${NACOS_PORT} -Djava.security.egd=file:/dev/.urandom -jar -Xms128m -Xmx256m /app/twelvet-server-system.jar'
    environment:
      - JAVA_OPTS=-Xmx256M
      - TZ=Asia/Shanghai

  twelvet-server-es:
    image: docker.io/java:8
    restart: always
    container_name: twelvet-es
    privileged: true
    network_mode: twelvet-network
    # 可以接受外部输入
    tty: true
    volumes:
      - /data/docker/twelvet/logs/twelvet-server-es:/logs
      - /data/docker/twelvet/twelvet-server-es:/app
    entrypoint: 'java -DNACOS_HOST=${NACOS_HOST} -DNACOS_PORT=${NACOS_PORT} -Djava.security.egd=file:/dev/.urandom -jar -Xms128m -Xmx256m /app/twelvet-server-es.jar'
    environment:
      - JAVA_OPTS=-Xmx256M
      - TZ=Asia/Shanghai

  twelvet-server-netty:
    image: docker.io/java:8
    restart: always
    container_name: twelvet-netty
    privileged: true
    network_mode: twelvet-network
    # 可以接受外部输入
    tty: true
    volumes:
      - /data/docker/twelvet/logs/twelvet-server-netty:/logs
      - /data/docker/twelvet/twelvet-server-netty:/app
    entrypoint: 'java -DNACOS_HOST=${NACOS_HOST} -DNACOS_PORT=${NACOS_PORT} -Djava.security.egd=file:/dev/.urandom -jar -Xms128m -Xmx256m /app/twelvet-server-netty.jar'
    environment:
      - JAVA_OPTS=-Xmx256M
      - TZ=Asia/Shanghai

  twelvet-server-mq:
    image: docker.io/java:8
    restart: always
    container_name: twelvet-es
    privileged: true
    network_mode: twelvet-network
    # 可以接受外部输入
    tty: true
    volumes:
      - /data/docker/twelvet/logs/twelvet-server-mq:/logs
      - /data/docker/twelvet/twelvet-server-mq:/app
    entrypoint: 'java -DNACOS_HOST=${NACOS_HOST} -DNACOS_PORT=${NACOS_PORT} -Djava.security.egd=file:/dev/.urandom -jar -Xms128m -Xmx256m /app/twelvet-server-mq.jar'
    environment:
      - JAVA_OPTS=-Xmx256M
      - TZ=Asia/Shanghai

  twelvet-server-job:
    image: docker.io/java:8
    restart: always
    container_name: twelvet-job
    privileged: true
    network_mode: twelvet-network
    # 可以接受外部输入
    tty: true
    volumes:
      - /data/docker/twelvet/logs/twelvet-server-job:/logs
      - /data/docker/twelvet/twelvet-server-job:/app
    entrypoint: 'java -DNACOS_HOST=${NACOS_HOST} -DNACOS_PORT=${NACOS_PORT} -Djava.security.egd=file:/dev/.urandom -jar -Xms128m -Xmx256m /app/twelvet-server-job.jar'
    environment:
      - JAVA_OPTS=-Xmx256M
      - TZ=Asia/Shanghai

  twelvet-visual-monitor:
    image: docker.io/java:8
    restart: always
    container_name: twelvet-monitor
    privileged: true
    network_mode: twelvet-network
    # 可以接受外部输入
    tty: true
    volumes:
      - /data/docker/twelvet/logs/twelvet-visual-monitor:/logs
      - /data/docker/twelvet/twelvet-visual-monitor:/app
    entrypoint: 'java -DNACOS_HOST=${NACOS_HOST} -DNACOS_PORT=${NACOS_PORT} -Djava.security.egd=file:/dev/.urandom -jar -Xms128m -Xmx256m /app/twelvet-monitor.jar'
    environment:
      - JAVA_OPTS=-Xmx256M
      - TZ=Asia/Shanghai

networks:
  twelvet-network:
    external:
      name: twelvet-network
