name: Build Test

on:
  push:
    branches: [ master-boot-3,spring-cloud-tencent ]
  pull_request:
    branches: [ master-boot-3,spring-cloud-tencent ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'twelvet'

      - name: mvn spring-javaformat:validate
        run: mvn spring-javaformat:validate

      - name: mvn clean install
        run: mvn clean install

      - name: Start containers
        run: docker/docker-compose build && docker/docker-compose up -d

      - name: failure
        if: failure() && github.repository == 'twelvet-s/twelvet'
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: |
            # 💤🤷‍♀️ failure 🙅‍♂️💣 [twelvet-s/twelvet](https://github.com/twelvet-s/twelvet)
            > Github Action: https://github.com/twelvet-s/twelvet failure
            > (⋟﹏⋞)   from github action message
